# Generated by Django 5.1.6 on 2025-02-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickOrder',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commans.basemodel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('commans.basemodel',),
        ),
    ]
